### ISSUE TITLE
Aggiunta e gestione ruoli utenti

### ISSUE THREAD

**Issue by sariodesign** [SaggeseNiccolo/NotebookStore#3]
Aggiungere i seguenti ruoli alle entità IdentityUser:
Admin - Editor - Viewer

Ogni ruolo potrà effettuare determinate azioni su NoteBook Store
Admin:
- [x] Può effettuare qualsiasi operazione sui modelli disponibili (esempi: creazione notebook, eliminazione brand, modifica cpu, creare nuovi utenti)
- [x] Sarà possibile avere solo 3 IdentityUser con ruolo Admin

Editor:
- [x] Può effettuare qualsiasi operazione sui modelli disponibili eccetto i notebook (esempi: aggiornare caratteristiche display, creare un nuovo cpu)

Viewer:
- [x] Può solo visualizzare i notebook disponibili

**extra per utente viewer**
- [ ] Può aggiungere i notebook in un a propria 'whishlist'

**Comment by 21sagge** [comment]
Gli utenti di ruolo diverso da Admin possono essere cancellati solo da utenti con ruolo Admin
Gli utenti admin non possono cancellare altri utenti admin (significa anche che un utente admin non può cancellare se stesso)
